#include<stdio.h>
#include<stdlib.h>
#include<math.h>
#include<time.h>

int wordscore(char word[])
{
    int score=0, i=0;
    while (word[i]!=0)
    {
        score += word[i]-64;
        i++;
    }
    return score;
}

int longestword(char word[][15])
{
    int i, j, size=0, sizemax = 0;
    for (i=0;i<1786;i++)
    {
        j=0;
        size = 0;
        while(word[i][j]!=0)
        {
            size++;
            j++;
        }

        if (sizemax<size) sizemax = size;
    }
    return sizemax;
}

void init_triangular_array(int tri[], int size)
{
    int i;
    tri[0] = 0;
    for (i=1;i<size;i++)
    {
        tri[i]=(i*(i+1))/2;
    }
}
// code function with adjustable array with every n term of triangular sequence it encounters
int dicho_triangular(int n, int tab[], int size)
{
    int m, g=0, d = size-1;
    printf("n = %d\n", n);
    while(g<=d)
    {
        m = (g+d)/2;
        if (tab[m]==n) 
        {
            return 1;
        }
        if (tab[m]>n) d = m-1;
        if (tab[m]<n) g = m+1;
    }
    return 0;
}

void euler42(char words[][15])
{
    int triangular[27];
    int size, i, total = 0, score;

    init_triangular_array(triangular, 27);
    size = longestword(words);

    for (i=0;i<1786;i++)
    {
        score = wordscore(words[i]);
        if (dicho_triangular(score, triangular, 27) == 1) total += 1;
    }
    printf("total : %d\n", total);
}   

int main()
{
    clock_t start, end;
    start = clock();

    char words[][15] = {"A\0",\
                "ABILITY\0",\
                "ABLE\0",\
                "ABOUT\0",\
                "ABOVE\0",\
                "ABSENCE\0",\
                "ABSOLUTELY\0",\
                "ACADEMIC\0",\
                "ACCEPT\0",\
                "ACCESS\0",\
                "ACCIDENT\0",\
                "ACCOMPANY\0",\
                "ACCORDING\0",\
                "ACCOUNT\0",\
                "ACHIEVE\0",\
                "ACHIEVEMENT\0",\
                "ACID\0",\
                "ACQUIRE\0",\
                "ACROSS\0",\
                "ACT\0",\
                "ACTION\0",\
                "ACTIVE\0",\
                "ACTIVITY\0",\
                "ACTUAL\0",\
                "ACTUALLY\0",\
                "ADD\0",\
                "ADDITION\0",\
                "ADDITIONAL\0",\
                "ADDRESS\0",\
                "ADMINISTRATION\0",\
                "ADMIT\0",\
                "ADOPT\0",\
                "ADULT\0",\
                "ADVANCE\0",\
                "ADVANTAGE\0",\
                "ADVICE\0",\
                "ADVISE\0",\
                "AFFAIR\0",\
                "AFFECT\0",\
                "AFFORD\0",\
                "AFRAID\0",\
                "AFTER\0",\
                "AFTERNOON\0",\
                "AFTERWARDS\0",\
                "AGAIN\0",\
                "AGAINST\0",\
                "AGE\0",\
                "AGENCY\0",\
                "AGENT\0",\
                "AGO\0",\
                "AGREE\0",\
                "AGREEMENT\0",\
                "AHEAD\0",\
                "AID\0",\
                "AIM\0",\
                "AIR\0",\
                "AIRCRAFT\0",\
                "ALL\0",\
                "ALLOW\0",\
                "ALMOST\0",\
                "ALONE\0",\
                "ALONG\0",\
                "ALREADY\0",\
                "ALRIGHT\0",\
                "ALSO\0",\
                "ALTERNATIVE\0",\
                "ALTHOUGH\0",\
                "ALWAYS\0",\
                "AMONG\0",\
                "AMONGST\0",\
                "AMOUNT\0",\
                "AN\0",\
                "ANALYSIS\0",\
                "ANCIENT\0",\
                "AND\0",\
                "ANIMAL\0",\
                "ANNOUNCE\0",\
                "ANNUAL\0",\
                "ANOTHER\0",\
                "ANSWER\0",\
                "ANY\0",\
                "ANYBODY\0",\
                "ANYONE\0",\
                "ANYTHING\0",\
                "ANYWAY\0",\
                "APART\0",\
                "APPARENT\0",\
                "APPARENTLY\0",\
                "APPEAL\0",\
                "APPEAR\0",\
                "APPEARANCE\0",\
                "APPLICATION\0",\
                "APPLY\0",\
                "APPOINT\0",\
                "APPOINTMENT\0",\
                "APPROACH\0",\
                "APPROPRIATE\0",\
                "APPROVE\0",\
                "AREA\0",\
                "ARGUE\0",\
                "ARGUMENT\0",\
                "ARISE\0",\
                "ARM\0",\
                "ARMY\0",\
                "AROUND\0",\
                "ARRANGE\0",\
                "ARRANGEMENT\0",\
                "ARRIVE\0",\
                "ART\0",\
                "ARTICLE\0",\
                "ARTIST\0",\
                "AS\0",\
                "ASK\0",\
                "ASPECT\0",\
                "ASSEMBLY\0",\
                "ASSESS\0",\
                "ASSESSMENT\0",\
                "ASSET\0",\
                "ASSOCIATE\0",\
                "ASSOCIATION\0",\
                "ASSUME\0",\
                "ASSUMPTION\0",\
                "AT\0",\
                "ATMOSPHERE\0",\
                "ATTACH\0",\
                "ATTACK\0",\
                "ATTEMPT\0",\
                "ATTEND\0",\
                "ATTENTION\0",\
                "ATTITUDE\0",\
                "ATTRACT\0",\
                "ATTRACTIVE\0",\
                "AUDIENCE\0",\
                "AUTHOR\0",\
                "AUTHORITY\0",\
                "AVAILABLE\0",\
                "AVERAGE\0",\
                "AVOID\0",\
                "AWARD\0",\
                "AWARE\0",\
                "AWAY\0",\
                "AYE\0",\
                "BABY\0",\
                "BACK\0",\
                "BACKGROUND\0",\
                "BAD\0",\
                "BAG\0",\
                "BALANCE\0",\
                "BALL\0",\
                "BAND\0",\
                "BANK\0",\
                "BAR\0",\
                "BASE\0",\
                "BASIC\0",\
                "BASIS\0",\
                "BATTLE\0",\
                "BE\0",\
                "BEAR\0",\
                "BEAT\0",\
                "BEAUTIFUL\0",\
                "BECAUSE\0",\
                "BECOME\0",\
                "BED\0",\
                "BEDROOM\0",\
                "BEFORE\0",\
                "BEGIN\0",\
                "BEGINNING\0",\
                "BEHAVIOUR\0",\
                "BEHIND\0",\
                "BELIEF\0",\
                "BELIEVE\0",\
                "BELONG\0",\
                "BELOW\0",\
                "BENEATH\0",\
                "BENEFIT\0",\
                "BESIDE\0",\
                "BEST\0",\
                "BETTER\0",\
                "BETWEEN\0",\
                "BEYOND\0",\
                "BIG\0",\
                "BILL\0",\
                "BIND\0",\
                "BIRD\0",\
                "BIRTH\0",\
                "BIT\0",\
                "BLACK\0",\
                "BLOCK\0",\
                "BLOOD\0",\
                "BLOODY\0",\
                "BLOW\0",\
                "BLUE\0",\
                "BOARD\0",\
                "BOAT\0",\
                "BODY\0",\
                "BONE\0",\
                "BOOK\0",\
                "BORDER\0",\
                "BOTH\0",\
                "BOTTLE\0",\
                "BOTTOM\0",\
                "BOX\0",\
                "BOY\0",\
                "BRAIN\0",\
                "BRANCH\0",\
                "BREAK\0",\
                "BREATH\0",\
                "BRIDGE\0",\
                "BRIEF\0",\
                "BRIGHT\0",\
                "BRING\0",\
                "BROAD\0",\
                "BROTHER\0",\
                "BUDGET\0",\
                "BUILD\0",\
                "BUILDING\0",\
                "BURN\0",\
                "BUS\0",\
                "BUSINESS\0",\
                "BUSY\0",\
                "BUT\0",\
                "BUY\0",\
                "BY\0",\
                "CABINET\0",\
                "CALL\0",\
                "CAMPAIGN\0",\
                "CAN\0",\
                "CANDIDATE\0",\
                "CAPABLE\0",\
                "CAPACITY\0",\
                "CAPITAL\0",\
                "CAR\0",\
                "CARD\0",\
                "CARE\0",\
                "CAREER\0",\
                "CAREFUL\0",\
                "CAREFULLY\0",\
                "CARRY\0",\
                "CASE\0",\
                "CASH\0",\
                "CAT\0",\
                "CATCH\0",\
                "CATEGORY\0",\
                "CAUSE\0",\
                "CELL\0",\
                "CENTRAL\0",\
                "CENTRE\0",\
                "CENTURY\0",\
                "CERTAIN\0",\
                "CERTAINLY\0",\
                "CHAIN\0",\
                "CHAIR\0",\
                "CHAIRMAN\0",\
                "CHALLENGE\0",\
                "CHANCE\0",\
                "CHANGE\0",\
                "CHANNEL\0",\
                "CHAPTER\0",\
                "CHARACTER\0",\
                "CHARACTERISTIC\0",\
                "CHARGE\0",\
                "CHEAP\0",\
                "CHECK\0",\
                "CHEMICAL\0",\
                "CHIEF\0",\
                "CHILD\0",\
                "CHOICE\0",\
                "CHOOSE\0",\
                "CHURCH\0",\
                "CIRCLE\0",\
                "CIRCUMSTANCE\0",\
                "CITIZEN\0",\
                "CITY\0",\
                "CIVIL\0",\
                "CLAIM\0",\
                "CLASS\0",\
                "CLEAN\0",\
                "CLEAR\0",\
                "CLEARLY\0",\
                "CLIENT\0",\
                "CLIMB\0",\
                "CLOSE\0",\
                "CLOSELY\0",\
                "CLOTHES\0",\
                "CLUB\0",\
                "COAL\0",\
                "CODE\0",\
                "COFFEE\0",\
                "COLD\0",\
                "COLLEAGUE\0",\
                "COLLECT\0",\
                "COLLECTION\0",\
                "COLLEGE\0",\
                "COLOUR\0",\
                "COMBINATION\0",\
                "COMBINE\0",\
                "COME\0",\
                "COMMENT\0",\
                "COMMERCIAL\0",\
                "COMMISSION\0",\
                "COMMIT\0",\
                "COMMITMENT\0",\
                "COMMITTEE\0",\
                "COMMON\0",\
                "COMMUNICATION\0",\
                "COMMUNITY\0",\
                "COMPANY\0",\
                "COMPARE\0",\
                "COMPARISON\0",\
                "COMPETITION\0",\
                "COMPLETE\0",\
                "COMPLETELY\0",\
                "COMPLEX\0",\
                "COMPONENT\0",\
                "COMPUTER\0",\
                "CONCENTRATE\0",\
                "CONCENTRATION\0",\
                "CONCEPT\0",\
                "CONCERN\0",\
                "CONCERNED\0",\
                "CONCLUDE\0",\
                "CONCLUSION\0",\
                "CONDITION\0",\
                "CONDUCT\0",\
                "CONFERENCE\0",\
                "CONFIDENCE\0",\
                "CONFIRM\0",\
                "CONFLICT\0",\
                "CONGRESS\0",\
                "CONNECT\0",\
                "CONNECTION\0",\
                "CONSEQUENCE\0",\
                "CONSERVATIVE\0",\
                "CONSIDER\0",\
                "CONSIDERABLE\0",\
                "CONSIDERATION\0",\
                "CONSIST\0",\
                "CONSTANT\0",\
                "CONSTRUCTION\0",\
                "CONSUMER\0",\
                "CONTACT\0",\
                "CONTAIN\0",\
                "CONTENT\0",\
                "CONTEXT\0",\
                "CONTINUE\0",\
                "CONTRACT\0",\
                "CONTRAST\0",\
                "CONTRIBUTE\0",\
                "CONTRIBUTION\0",\
                "CONTROL\0",\
                "CONVENTION\0",\
                "CONVERSATION\0",\
                "COPY\0",\
                "CORNER\0",\
                "CORPORATE\0",\
                "CORRECT\0",\
                "COS\0",\
                "COST\0",\
                "COULD\0",\
                "COUNCIL\0",\
                "COUNT\0",\
                "COUNTRY\0",\
                "COUNTY\0",\
                "COUPLE\0",\
                "COURSE\0",\
                "COURT\0",\
                "COVER\0",\
                "CREATE\0",\
                "CREATION\0",\
                "CREDIT\0",\
                "CRIME\0",\
                "CRIMINAL\0",\
                "CRISIS\0",\
                "CRITERION\0",\
                "CRITICAL\0",\
                "CRITICISM\0",\
                "CROSS\0",\
                "CROWD\0",\
                "CRY\0",\
                "CULTURAL\0",\
                "CULTURE\0",\
                "CUP\0",\
                "CURRENT\0",\
                "CURRENTLY\0",\
                "CURRICULUM\0",\
                "CUSTOMER\0",\
                "CUT\0",\
                "DAMAGE\0",\
                "DANGER\0",\
                "DANGEROUS\0",\
                "DARK\0",\
                "DATA\0",\
                "DATE\0",\
                "DAUGHTER\0",\
                "DAY\0",\
                "DEAD\0",\
                "DEAL\0",\
                "DEATH\0",\
                "DEBATE\0",\
                "DEBT\0",\
                "DECADE\0",\
                "DECIDE\0",\
                "DECISION\0",\
                "DECLARE\0",\
                "DEEP\0",\
                "DEFENCE\0",\
                "DEFENDANT\0",\
                "DEFINE\0",\
                "DEFINITION\0",\
                "DEGREE\0",\
                "DELIVER\0",\
                "DEMAND\0",\
                "DEMOCRATIC\0",\
                "DEMONSTRATE\0",\
                "DENY\0",\
                "DEPARTMENT\0",\
                "DEPEND\0",\
                "DEPUTY\0",\
                "DERIVE\0",\
                "DESCRIBE\0",\
                "DESCRIPTION\0",\
                "DESIGN\0",\
                "DESIRE\0",\
                "DESK\0",\
                "DESPITE\0",\
                "DESTROY\0",\
                "DETAIL\0",\
                "DETAILED\0",\
                "DETERMINE\0",\
                "DEVELOP\0",\
                "DEVELOPMENT\0",\
                "DEVICE\0",\
                "DIE\0",\
                "DIFFERENCE\0",\
                "DIFFERENT\0",\
                "DIFFICULT\0",\
                "DIFFICULTY\0",\
                "DINNER\0",\
                "DIRECT\0",\
                "DIRECTION\0",\
                "DIRECTLY\0",\
                "DIRECTOR\0",\
                "DISAPPEAR\0",\
                "DISCIPLINE\0",\
                "DISCOVER\0",\
                "DISCUSS\0",\
                "DISCUSSION\0",\
                "DISEASE\0",\
                "DISPLAY\0",\
                "DISTANCE\0",\
                "DISTINCTION\0",\
                "DISTRIBUTION\0",\
                "DISTRICT\0",\
                "DIVIDE\0",\
                "DIVISION\0",\
                "DO\0",\
                "DOCTOR\0",\
                "DOCUMENT\0",\
                "DOG\0",\
                "DOMESTIC\0",\
                "DOOR\0",\
                "DOUBLE\0",\
                "DOUBT\0",\
                "DOWN\0",\
                "DRAW\0",\
                "DRAWING\0",\
                "DREAM\0",\
                "DRESS\0",\
                "DRINK\0",\
                "DRIVE\0",\
                "DRIVER\0",\
                "DROP\0",\
                "DRUG\0",\
                "DRY\0",\
                "DUE\0",\
                "DURING\0",\
                "DUTY\0",\
                "EACH\0",\
                "EAR\0",\
                "EARLY\0",\
                "EARN\0",\
                "EARTH\0",\
                "EASILY\0",\
                "EAST\0",\
                "EASY\0",\
                "EAT\0",\
                "ECONOMIC\0",\
                "ECONOMY\0",\
                "EDGE\0",\
                "EDITOR\0",\
                "EDUCATION\0",\
                "EDUCATIONAL\0",\
                "EFFECT\0",\
                "EFFECTIVE\0",\
                "EFFECTIVELY\0",\
                "EFFORT\0",\
                "EGG\0",\
                "EITHER\0",\
                "ELDERLY\0",\
                "ELECTION\0",\
                "ELEMENT\0",\
                "ELSE\0",\
                "ELSEWHERE\0",\
                "EMERGE\0",\
                "EMPHASIS\0",\
                "EMPLOY\0",\
                "EMPLOYEE\0",\
                "EMPLOYER\0",\
                "EMPLOYMENT\0",\
                "EMPTY\0",\
                "ENABLE\0",\
                "ENCOURAGE\0",\
                "END\0",\
                "ENEMY\0",\
                "ENERGY\0",\
                "ENGINE\0",\
                "ENGINEERING\0",\
                "ENJOY\0",\
                "ENOUGH\0",\
                "ENSURE\0",\
                "ENTER\0",\
                "ENTERPRISE\0",\
                "ENTIRE\0",\
                "ENTIRELY\0",\
                "ENTITLE\0",\
                "ENTRY\0",\
                "ENVIRONMENT\0",\
                "ENVIRONMENTAL\0",\
                "EQUAL\0",\
                "EQUALLY\0",\
                "EQUIPMENT\0",\
                "ERROR\0",\
                "ESCAPE\0",\
                "ESPECIALLY\0",\
                "ESSENTIAL\0",\
                "ESTABLISH\0",\
                "ESTABLISHMENT\0",\
                "ESTATE\0",\
                "ESTIMATE\0",\
                "EVEN\0",\
                "EVENING\0",\
                "EVENT\0",\
                "EVENTUALLY\0",\
                "EVER\0",\
                "EVERY\0",\
                "EVERYBODY\0",\
                "EVERYONE\0",\
                "EVERYTHING\0",\
                "EVIDENCE\0",\
                "EXACTLY\0",\
                "EXAMINATION\0",\
                "EXAMINE\0",\
                "EXAMPLE\0",\
                "EXCELLENT\0",\
                "EXCEPT\0",\
                "EXCHANGE\0",\
                "EXECUTIVE\0",\
                "EXERCISE\0",\
                "EXHIBITION\0",\
                "EXIST\0",\
                "EXISTENCE\0",\
                "EXISTING\0",\
                "EXPECT\0",\
                "EXPECTATION\0",\
                "EXPENDITURE\0",\
                "EXPENSE\0",\
                "EXPENSIVE\0",\
                "EXPERIENCE\0",\
                "EXPERIMENT\0",\
                "EXPERT\0",\
                "EXPLAIN\0",\
                "EXPLANATION\0",\
                "EXPLORE\0",\
                "EXPRESS\0",\
                "EXPRESSION\0",\
                "EXTEND\0",\
                "EXTENT\0",\
                "EXTERNAL\0",\
                "EXTRA\0",\
                "EXTREMELY\0",\
                "EYE\0",\
                "FACE\0",\
                "FACILITY\0",\
                "FACT\0",\
                "FACTOR\0",\
                "FACTORY\0",\
                "FAIL\0",\
                "FAILURE\0",\
                "FAIR\0",\
                "FAIRLY\0",\
                "FAITH\0",\
                "FALL\0",\
                "FAMILIAR\0",\
                "FAMILY\0",\
                "FAMOUS\0",\
                "FAR\0",\
                "FARM\0",\
                "FARMER\0",\
                "FASHION\0",\
                "FAST\0",\
                "FATHER\0",\
                "FAVOUR\0",\
                "FEAR\0",\
                "FEATURE\0",\
                "FEE\0",\
                "FEEL\0",\
                "FEELING\0",\
                "FEMALE\0",\
                "FEW\0",\
                "FIELD\0",\
                "FIGHT\0",\
                "FIGURE\0",\
                "FILE\0",\
                "FILL\0",\
                "FILM\0",\
                "FINAL\0",\
                "FINALLY\0",\
                "FINANCE\0",\
                "FINANCIAL\0",\
                "FIND\0",\
                "FINDING\0",\
                "FINE\0",\
                "FINGER\0",\
                "FINISH\0",\
                "FIRE\0",\
                "FIRM\0",\
                "FIRST\0",\
                "FISH\0",\
                "FIT\0",\
                "FIX\0",\
                "FLAT\0",\
                "FLIGHT\0",\
                "FLOOR\0",\
                "FLOW\0",\
                "FLOWER\0",\
                "FLY\0",\
                "FOCUS\0",\
                "FOLLOW\0",\
                "FOLLOWING\0",\
                "FOOD\0",\
                "FOOT\0",\
                "FOOTBALL\0",\
                "FOR\0",\
                "FORCE\0",\
                "FOREIGN\0",\
                "FOREST\0",\
                "FORGET\0",\
                "FORM\0",\
                "FORMAL\0",\
                "FORMER\0",\
                "FORWARD\0",\
                "FOUNDATION\0",\
                "FREE\0",\
                "FREEDOM\0",\
                "FREQUENTLY\0",\
                "FRESH\0",\
                "FRIEND\0",\
                "FROM\0",\
                "FRONT\0",\
                "FRUIT\0",\
                "FUEL\0",\
                "FULL\0",\
                "FULLY\0",\
                "FUNCTION\0",\
                "FUND\0",\
                "FUNNY\0",\
                "FURTHER\0",\
                "FUTURE\0",\
                "GAIN\0",\
                "GAME\0",\
                "GARDEN\0",\
                "GAS\0",\
                "GATE\0",\
                "GATHER\0",\
                "GENERAL\0",\
                "GENERALLY\0",\
                "GENERATE\0",\
                "GENERATION\0",\
                "GENTLEMAN\0",\
                "GET\0",\
                "GIRL\0",\
                "GIVE\0",\
                "GLASS\0",\
                "GO\0",\
                "GOAL\0",\
                "GOD\0",\
                "GOLD\0",\
                "GOOD\0",\
                "GOVERNMENT\0",\
                "GRANT\0",\
                "GREAT\0",\
                "GREEN\0",\
                "GREY\0",\
                "GROUND\0",\
                "GROUP\0",\
                "GROW\0",\
                "GROWING\0",\
                "GROWTH\0",\
                "GUEST\0",\
                "GUIDE\0",\
                "GUN\0",\
                "HAIR\0",\
                "HALF\0",\
                "HALL\0",\
                "HAND\0",\
                "HANDLE\0",\
                "HANG\0",\
                "HAPPEN\0",\
                "HAPPY\0",\
                "HARD\0",\
                "HARDLY\0",\
                "HATE\0",\
                "HAVE\0",\
                "HE\0",\
                "HEAD\0",\
                "HEALTH\0",\
                "HEAR\0",\
                "HEART\0",\
                "HEAT\0",\
                "HEAVY\0",\
                "HELL\0",\
                "HELP\0",\
                "HENCE\0",\
                "HER\0",\
                "HERE\0",\
                "HERSELF\0",\
                "HIDE\0",\
                "HIGH\0",\
                "HIGHLY\0",\
                "HILL\0",\
                "HIM\0",\
                "HIMSELF\0",\
                "HIS\0",\
                "HISTORICAL\0",\
                "HISTORY\0",\
                "HIT\0",\
                "HOLD\0",\
                "HOLE\0",\
                "HOLIDAY\0",\
                "HOME\0",\
                "HOPE\0",\
                "HORSE\0",\
                "HOSPITAL\0",\
                "HOT\0",\
                "HOTEL\0",\
                "HOUR\0",\
                "HOUSE\0",\
                "HOUSEHOLD\0",\
                "HOUSING\0",\
                "HOW\0",\
                "HOWEVER\0",\
                "HUGE\0",\
                "HUMAN\0",\
                "HURT\0",\
                "HUSBAND\0",\
                "I\0",\
                "IDEA\0",\
                "IDENTIFY\0",\
                "IF\0",\
                "IGNORE\0",\
                "ILLUSTRATE\0",\
                "IMAGE\0",\
                "IMAGINE\0",\
                "IMMEDIATE\0",\
                "IMMEDIATELY\0",\
                "IMPACT\0",\
                "IMPLICATION\0",\
                "IMPLY\0",\
                "IMPORTANCE\0",\
                "IMPORTANT\0",\
                "IMPOSE\0",\
                "IMPOSSIBLE\0",\
                "IMPRESSION\0",\
                "IMPROVE\0",\
                "IMPROVEMENT\0",\
                "IN\0",\
                "INCIDENT\0",\
                "INCLUDE\0",\
                "INCLUDING\0",\
                "INCOME\0",\
                "INCREASE\0",\
                "INCREASED\0",\
                "INCREASINGLY\0",\
                "INDEED\0",\
                "INDEPENDENT\0",\
                "INDEX\0",\
                "INDICATE\0",\
                "INDIVIDUAL\0",\
                "INDUSTRIAL\0",\
                "INDUSTRY\0",\
                "INFLUENCE\0",\
                "INFORM\0",\
                "INFORMATION\0",\
                "INITIAL\0",\
                "INITIATIVE\0",\
                "INJURY\0",\
                "INSIDE\0",\
                "INSIST\0",\
                "INSTANCE\0",\
                "INSTEAD\0",\
                "INSTITUTE\0",\
                "INSTITUTION\0",\
                "INSTRUCTION\0",\
                "INSTRUMENT\0",\
                "INSURANCE\0",\
                "INTEND\0",\
                "INTENTION\0",\
                "INTEREST\0",\
                "INTERESTED\0",\
                "INTERESTING\0",\
                "INTERNAL\0",\
                "INTERNATIONAL\0",\
                "INTERPRETATION\0",\
                "INTERVIEW\0",\
                "INTO\0",\
                "INTRODUCE\0",\
                "INTRODUCTION\0",\
                "INVESTIGATE\0",\
                "INVESTIGATION\0",\
                "INVESTMENT\0",\
                "INVITE\0",\
                "INVOLVE\0",\
                "IRON\0",\
                "IS\0",\
                "ISLAND\0",\
                "ISSUE\0",\
                "IT\0",\
                "ITEM\0",\
                "ITS\0",\
                "ITSELF\0",\
                "JOB\0",\
                "JOIN\0",\
                "JOINT\0",\
                "JOURNEY\0",\
                "JUDGE\0",\
                "JUMP\0",\
                "JUST\0",\
                "JUSTICE\0",\
                "KEEP\0",\
                "KEY\0",\
                "KID\0",\
                "KILL\0",\
                "KIND\0",\
                "KING\0",\
                "KITCHEN\0",\
                "KNEE\0",\
                "KNOW\0",\
                "KNOWLEDGE\0",\
                "LABOUR\0",\
                "LACK\0",\
                "LADY\0",\
                "LAND\0",\
                "LANGUAGE\0",\
                "LARGE\0",\
                "LARGELY\0",\
                "LAST\0",\
                "LATE\0",\
                "LATER\0",\
                "LATTER\0",\
                "LAUGH\0",\
                "LAUNCH\0",\
                "LAW\0",\
                "LAWYER\0",\
                "LAY\0",\
                "LEAD\0",\
                "LEADER\0",\
                "LEADERSHIP\0",\
                "LEADING\0",\
                "LEAF\0",\
                "LEAGUE\0",\
                "LEAN\0",\
                "LEARN\0",\
                "LEAST\0",\
                "LEAVE\0",\
                "LEFT\0",\
                "LEG\0",\
                "LEGAL\0",\
                "LEGISLATION\0",\
                "LENGTH\0",\
                "LESS\0",\
                "LET\0",\
                "LETTER\0",\
                "LEVEL\0",\
                "LIABILITY\0",\
                "LIBERAL\0",\
                "LIBRARY\0",\
                "LIE\0",\
                "LIFE\0",\
                "LIFT\0",\
                "LIGHT\0",\
                "LIKE\0",\
                "LIKELY\0",\
                "LIMIT\0",\
                "LIMITED\0",\
                "LINE\0",\
                "LINK\0",\
                "LIP\0",\
                "LIST\0",\
                "LISTEN\0",\
                "LITERATURE\0",\
                "LITTLE\0",\
                "LIVE\0",\
                "LIVING\0",\
                "LOAN\0",\
                "LOCAL\0",\
                "LOCATION\0",\
                "LONG\0",\
                "LOOK\0",\
                "LORD\0",\
                "LOSE\0",\
                "LOSS\0",\
                "LOT\0",\
                "LOVE\0",\
                "LOVELY\0",\
                "LOW\0",\
                "LUNCH\0",\
                "MACHINE\0",\
                "MAGAZINE\0",\
                "MAIN\0",\
                "MAINLY\0",\
                "MAINTAIN\0",\
                "MAJOR\0",\
                "MAJORITY\0",\
                "MAKE\0",\
                "MALE\0",\
                "MAN\0",\
                "MANAGE\0",\
                "MANAGEMENT\0",\
                "MANAGER\0",\
                "MANNER\0",\
                "MANY\0",\
                "MAP\0",\
                "MARK\0",\
                "MARKET\0",\
                "MARRIAGE\0",\
                "MARRIED\0",\
                "MARRY\0",\
                "MASS\0",\
                "MASTER\0",\
                "MATCH\0",\
                "MATERIAL\0",\
                "MATTER\0",\
                "MAY\0",\
                "MAYBE\0",\
                "ME\0",\
                "MEAL\0",\
                "MEAN\0",\
                "MEANING\0",\
                "MEANS\0",\
                "MEANWHILE\0",\
                "MEASURE\0",\
                "MECHANISM\0",\
                "MEDIA\0",\
                "MEDICAL\0",\
                "MEET\0",\
                "MEETING\0",\
                "MEMBER\0",\
                "MEMBERSHIP\0",\
                "MEMORY\0",\
                "MENTAL\0",\
                "MENTION\0",\
                "MERELY\0",\
                "MESSAGE\0",\
                "METAL\0",\
                "METHOD\0",\
                "MIDDLE\0",\
                "MIGHT\0",\
                "MILE\0",\
                "MILITARY\0",\
                "MILK\0",\
                "MIND\0",\
                "MINE\0",\
                "MINISTER\0",\
                "MINISTRY\0",\
                "MINUTE\0",\
                "MISS\0",\
                "MISTAKE\0",\
                "MODEL\0",\
                "MODERN\0",\
                "MODULE\0",\
                "MOMENT\0",\
                "MONEY\0",\
                "MONTH\0",\
                "MORE\0",\
                "MORNING\0",\
                "MOST\0",\
                "MOTHER\0",\
                "MOTION\0",\
                "MOTOR\0",\
                "MOUNTAIN\0",\
                "MOUTH\0",\
                "MOVE\0",\
                "MOVEMENT\0",\
                "MUCH\0",\
                "MURDER\0",\
                "MUSEUM\0",\
                "MUSIC\0",\
                "MUST\0",\
                "MY\0",\
                "MYSELF\0",\
                "NAME\0",\
                "NARROW\0",\
                "NATION\0",\
                "NATIONAL\0",\
                "NATURAL\0",\
                "NATURE\0",\
                "NEAR\0",\
                "NEARLY\0",\
                "NECESSARILY\0",\
                "NECESSARY\0",\
                "NECK\0",\
                "NEED\0",\
                "NEGOTIATION\0",\
                "NEIGHBOUR\0",\
                "NEITHER\0",\
                "NETWORK\0",\
                "NEVER\0",\
                "NEVERTHELESS\0",\
                "NEW\0",\
                "NEWS\0",\
                "NEWSPAPER\0",\
                "NEXT\0",\
                "NICE\0",\
                "NIGHT\0",\
                "NO\0",\
                "NOBODY\0",\
                "NOD\0",\
                "NOISE\0",\
                "NONE\0",\
                "NOR\0",\
                "NORMAL\0",\
                "NORMALLY\0",\
                "NORTH\0",\
                "NORTHERN\0",\
                "NOSE\0",\
                "NOT\0",\
                "NOTE\0",\
                "NOTHING\0",\
                "NOTICE\0",\
                "NOTION\0",\
                "NOW\0",\
                "NUCLEAR\0",\
                "NUMBER\0",\
                "NURSE\0",\
                "OBJECT\0",\
                "OBJECTIVE\0",\
                "OBSERVATION\0",\
                "OBSERVE\0",\
                "OBTAIN\0",\
                "OBVIOUS\0",\
                "OBVIOUSLY\0",\
                "OCCASION\0",\
                "OCCUR\0",\
                "ODD\0",\
                "OF\0",\
                "OFF\0",\
                "OFFENCE\0",\
                "OFFER\0",\
                "OFFICE\0",\
                "OFFICER\0",\
                "OFFICIAL\0",\
                "OFTEN\0",\
                "OIL\0",\
                "OKAY\0",\
                "OLD\0",\
                "ON\0",\
                "ONCE\0",\
                "ONE\0",\
                "ONLY\0",\
                "ONTO\0",\
                "OPEN\0",\
                "OPERATE\0",\
                "OPERATION\0",\
                "OPINION\0",\
                "OPPORTUNITY\0",\
                "OPPOSITION\0",\
                "OPTION\0",\
                "OR\0",\
                "ORDER\0",\
                "ORDINARY\0",\
                "ORGANISATION\0",\
                "ORGANISE\0",\
                "ORGANIZATION\0",\
                "ORIGIN\0",\
                "ORIGINAL\0",\
                "OTHER\0",\
                "OTHERWISE\0",\
                "OUGHT\0",\
                "OUR\0",\
                "OURSELVES\0",\
                "OUT\0",\
                "OUTCOME\0",\
                "OUTPUT\0",\
                "OUTSIDE\0",\
                "OVER\0",\
                "OVERALL\0",\
                "OWN\0",\
                "OWNER\0",\
                "PACKAGE\0",\
                "PAGE\0",\
                "PAIN\0",\
                "PAINT\0",\
                "PAINTING\0",\
                "PAIR\0",\
                "PANEL\0",\
                "PAPER\0",\
                "PARENT\0",\
                "PARK\0",\
                "PARLIAMENT\0",\
                "PART\0",\
                "PARTICULAR\0",\
                "PARTICULARLY\0",\
                "PARTLY\0",\
                "PARTNER\0",\
                "PARTY\0",\
                "PASS\0",\
                "PASSAGE\0",\
                "PAST\0",\
                "PATH\0",\
                "PATIENT\0",\
                "PATTERN\0",\
                "PAY\0",\
                "PAYMENT\0",\
                "PEACE\0",\
                "PENSION\0",\
                "PEOPLE\0",\
                "PER\0",\
                "PERCENT\0",\
                "PERFECT\0",\
                "PERFORM\0",\
                "PERFORMANCE\0",\
                "PERHAPS\0",\
                "PERIOD\0",\
                "PERMANENT\0",\
                "PERSON\0",\
                "PERSONAL\0",\
                "PERSUADE\0",\
                "PHASE\0",\
                "PHONE\0",\
                "PHOTOGRAPH\0",\
                "PHYSICAL\0",\
                "PICK\0",\
                "PICTURE\0",\
                "PIECE\0",\
                "PLACE\0",\
                "PLAN\0",\
                "PLANNING\0",\
                "PLANT\0",\
                "PLASTIC\0",\
                "PLATE\0",\
                "PLAY\0",\
                "PLAYER\0",\
                "PLEASE\0",\
                "PLEASURE\0",\
                "PLENTY\0",\
                "PLUS\0",\
                "POCKET\0",\
                "POINT\0",\
                "POLICE\0",\
                "POLICY\0",\
                "POLITICAL\0",\
                "POLITICS\0",\
                "POOL\0",\
                "POOR\0",\
                "POPULAR\0",\
                "POPULATION\0",\
                "POSITION\0",\
                "POSITIVE\0",\
                "POSSIBILITY\0",\
                "POSSIBLE\0",\
                "POSSIBLY\0",\
                "POST\0",\
                "POTENTIAL\0",\
                "POUND\0",\
                "POWER\0",\
                "POWERFUL\0",\
                "PRACTICAL\0",\
                "PRACTICE\0",\
                "PREFER\0",\
                "PREPARE\0",\
                "PRESENCE\0",\
                "PRESENT\0",\
                "PRESIDENT\0",\
                "PRESS\0",\
                "PRESSURE\0",\
                "PRETTY\0",\
                "PREVENT\0",\
                "PREVIOUS\0",\
                "PREVIOUSLY\0",\
                "PRICE\0",\
                "PRIMARY\0",\
                "PRIME\0",\
                "PRINCIPLE\0",\
                "PRIORITY\0",\
                "PRISON\0",\
                "PRISONER\0",\
                "PRIVATE\0",\
                "PROBABLY\0",\
                "PROBLEM\0",\
                "PROCEDURE\0",\
                "PROCESS\0",\
                "PRODUCE\0",\
                "PRODUCT\0",\
                "PRODUCTION\0",\
                "PROFESSIONAL\0",\
                "PROFIT\0",\
                "PROGRAM\0",\
                "PROGRAMME\0",\
                "PROGRESS\0",\
                "PROJECT\0",\
                "PROMISE\0",\
                "PROMOTE\0",\
                "PROPER\0",\
                "PROPERLY\0",\
                "PROPERTY\0",\
                "PROPORTION\0",\
                "PROPOSE\0",\
                "PROPOSAL\0",\
                "PROSPECT\0",\
                "PROTECT\0",\
                "PROTECTION\0",\
                "PROVE\0",\
                "PROVIDE\0",\
                "PROVIDED\0",\
                "PROVISION\0",\
                "PUB\0",\
                "PUBLIC\0",\
                "PUBLICATION\0",\
                "PUBLISH\0",\
                "PULL\0",\
                "PUPIL\0",\
                "PURPOSE\0",\
                "PUSH\0",\
                "PUT\0",\
                "QUALITY\0",\
                "QUARTER\0",\
                "QUESTION\0",\
                "QUICK\0",\
                "QUICKLY\0",\
                "QUIET\0",\
                "QUITE\0",\
                "RACE\0",\
                "RADIO\0",\
                "RAILWAY\0",\
                "RAIN\0",\
                "RAISE\0",\
                "RANGE\0",\
                "RAPIDLY\0",\
                "RARE\0",\
                "RATE\0",\
                "RATHER\0",\
                "REACH\0",\
                "REACTION\0",\
                "READ\0",\
                "READER\0",\
                "READING\0",\
                "READY\0",\
                "REAL\0",\
                "REALISE\0",\
                "REALITY\0",\
                "REALIZE\0",\
                "REALLY\0",\
                "REASON\0",\
                "REASONABLE\0",\
                "RECALL\0",\
                "RECEIVE\0",\
                "RECENT\0",\
                "RECENTLY\0",\
                "RECOGNISE\0",\
                "RECOGNITION\0",\
                "RECOGNIZE\0",\
                "RECOMMEND\0",\
                "RECORD\0",\
                "RECOVER\0",\
                "RED\0",\
                "REDUCE\0",\
                "REDUCTION\0",\
                "REFER\0",\
                "REFERENCE\0",\
                "REFLECT\0",\
                "REFORM\0",\
                "REFUSE\0",\
                "REGARD\0",\
                "REGION\0",\
                "REGIONAL\0",\
                "REGULAR\0",\
                "REGULATION\0",\
                "REJECT\0",\
                "RELATE\0",\
                "RELATION\0",\
                "RELATIONSHIP\0",\
                "RELATIVE\0",\
                "RELATIVELY\0",\
                "RELEASE\0",\
                "RELEVANT\0",\
                "RELIEF\0",\
                "RELIGION\0",\
                "RELIGIOUS\0",\
                "RELY\0",\
                "REMAIN\0",\
                "REMEMBER\0",\
                "REMIND\0",\
                "REMOVE\0",\
                "REPEAT\0",\
                "REPLACE\0",\
                "REPLY\0",\
                "REPORT\0",\
                "REPRESENT\0",\
                "REPRESENTATION\0",\
                "REPRESENTATIVE\0",\
                "REQUEST\0",\
                "REQUIRE\0",\
                "REQUIREMENT\0",\
                "RESEARCH\0",\
                "RESOURCE\0",\
                "RESPECT\0",\
                "RESPOND\0",\
                "RESPONSE\0",\
                "RESPONSIBILITY\0",\
                "RESPONSIBLE\0",\
                "REST\0",\
                "RESTAURANT\0",\
                "RESULT\0",\
                "RETAIN\0",\
                "RETURN\0",\
                "REVEAL\0",\
                "REVENUE\0",\
                "REVIEW\0",\
                "REVOLUTION\0",\
                "RICH\0",\
                "RIDE\0",\
                "RIGHT\0",\
                "RING\0",\
                "RISE\0",\
                "RISK\0",\
                "RIVER\0",\
                "ROAD\0",\
                "ROCK\0",\
                "ROLE\0",\
                "ROLL\0",\
                "ROOF\0",\
                "ROOM\0",\
                "ROUND\0",\
                "ROUTE\0",\
                "ROW\0",\
                "ROYAL\0",\
                "RULE\0",\
                "RUN\0",\
                "RURAL\0",\
                "SAFE\0",\
                "SAFETY\0",\
                "SALE\0",\
                "SAME\0",\
                "SAMPLE\0",\
                "SATISFY\0",\
                "SAVE\0",\
                "SAY\0",\
                "SCALE\0",\
                "SCENE\0",\
                "SCHEME\0",\
                "SCHOOL\0",\
                "SCIENCE\0",\
                "SCIENTIFIC\0",\
                "SCIENTIST\0",\
                "SCORE\0",\
                "SCREEN\0",\
                "SEA\0",\
                "SEARCH\0",\
                "SEASON\0",\
                "SEAT\0",\
                "SECOND\0",\
                "SECONDARY\0",\
                "SECRETARY\0",\
                "SECTION\0",\
                "SECTOR\0",\
                "SECURE\0",\
                "SECURITY\0",\
                "SEE\0",\
                "SEEK\0",\
                "SEEM\0",\
                "SELECT\0",\
                "SELECTION\0",\
                "SELL\0",\
                "SEND\0",\
                "SENIOR\0",\
                "SENSE\0",\
                "SENTENCE\0",\
                "SEPARATE\0",\
                "SEQUENCE\0",\
                "SERIES\0",\
                "SERIOUS\0",\
                "SERIOUSLY\0",\
                "SERVANT\0",\
                "SERVE\0",\
                "SERVICE\0",\
                "SESSION\0",\
                "SET\0",\
                "SETTLE\0",\
                "SETTLEMENT\0",\
                "SEVERAL\0",\
                "SEVERE\0",\
                "SEX\0",\
                "SEXUAL\0",\
                "SHAKE\0",\
                "SHALL\0",\
                "SHAPE\0",\
                "SHARE\0",\
                "SHE\0",\
                "SHEET\0",\
                "SHIP\0",\
                "SHOE\0",\
                "SHOOT\0",\
                "SHOP\0",\
                "SHORT\0",\
                "SHOT\0",\
                "SHOULD\0",\
                "SHOULDER\0",\
                "SHOUT\0",\
                "SHOW\0",\
                "SHUT\0",\
                "SIDE\0",\
                "SIGHT\0",\
                "SIGN\0",\
                "SIGNAL\0",\
                "SIGNIFICANCE\0",\
                "SIGNIFICANT\0",\
                "SILENCE\0",\
                "SIMILAR\0",\
                "SIMPLE\0",\
                "SIMPLY\0",\
                "SINCE\0",\
                "SING\0",\
                "SINGLE\0",\
                "SIR\0",\
                "SISTER\0",\
                "SIT\0",\
                "SITE\0",\
                "SITUATION\0",\
                "SIZE\0",\
                "SKILL\0",\
                "SKIN\0",\
                "SKY\0",\
                "SLEEP\0",\
                "SLIGHTLY\0",\
                "SLIP\0",\
                "SLOW\0",\
                "SLOWLY\0",\
                "SMALL\0",\
                "SMILE\0",\
                "SO\0",\
                "SOCIAL\0",\
                "SOCIETY\0",\
                "SOFT\0",\
                "SOFTWARE\0",\
                "SOIL\0",\
                "SOLDIER\0",\
                "SOLICITOR\0",\
                "SOLUTION\0",\
                "SOME\0",\
                "SOMEBODY\0",\
                "SOMEONE\0",\
                "SOMETHING\0",\
                "SOMETIMES\0",\
                "SOMEWHAT\0",\
                "SOMEWHERE\0",\
                "SON\0",\
                "SONG\0",\
                "SOON\0",\
                "SORRY\0",\
                "SORT\0",\
                "SOUND\0",\
                "SOURCE\0",\
                "SOUTH\0",\
                "SOUTHERN\0",\
                "SPACE\0",\
                "SPEAK\0",\
                "SPEAKER\0",\
                "SPECIAL\0",\
                "SPECIES\0",\
                "SPECIFIC\0",\
                "SPEECH\0",\
                "SPEED\0",\
                "SPEND\0",\
                "SPIRIT\0",\
                "SPORT\0",\
                "SPOT\0",\
                "SPREAD\0",\
                "SPRING\0",\
                "STAFF\0",\
                "STAGE\0",\
                "STAND\0",\
                "STANDARD\0",\
                "STAR\0",\
                "START\0",\
                "STATE\0",\
                "STATEMENT\0",\
                "STATION\0",\
                "STATUS\0",\
                "STAY\0",\
                "STEAL\0",\
                "STEP\0",\
                "STICK\0",\
                "STILL\0",\
                "STOCK\0",\
                "STONE\0",\
                "STOP\0",\
                "STORE\0",\
                "STORY\0",\
                "STRAIGHT\0",\
                "STRANGE\0",\
                "STRATEGY\0",\
                "STREET\0",\
                "STRENGTH\0",\
                "STRIKE\0",\
                "STRONG\0",\
                "STRONGLY\0",\
                "STRUCTURE\0",\
                "STUDENT\0",\
                "STUDIO\0",\
                "STUDY\0",\
                "STUFF\0",\
                "STYLE\0",\
                "SUBJECT\0",\
                "SUBSTANTIAL\0",\
                "SUCCEED\0",\
                "SUCCESS\0",\
                "SUCCESSFUL\0",\
                "SUCH\0",\
                "SUDDENLY\0",\
                "SUFFER\0",\
                "SUFFICIENT\0",\
                "SUGGEST\0",\
                "SUGGESTION\0",\
                "SUITABLE\0",\
                "SUM\0",\
                "SUMMER\0",\
                "SUN\0",\
                "SUPPLY\0",\
                "SUPPORT\0",\
                "SUPPOSE\0",\
                "SURE\0",\
                "SURELY\0",\
                "SURFACE\0",\
                "SURPRISE\0",\
                "SURROUND\0",\
                "SURVEY\0",\
                "SURVIVE\0",\
                "SWITCH\0",\
                "SYSTEM\0",\
                "TABLE\0",\
                "TAKE\0",\
                "TALK\0",\
                "TALL\0",\
                "TAPE\0",\
                "TARGET\0",\
                "TASK\0",\
                "TAX\0",\
                "TEA\0",\
                "TEACH\0",\
                "TEACHER\0",\
                "TEACHING\0",\
                "TEAM\0",\
                "TEAR\0",\
                "TECHNICAL\0",\
                "TECHNIQUE\0",\
                "TECHNOLOGY\0",\
                "TELEPHONE\0",\
                "TELEVISION\0",\
                "TELL\0",\
                "TEMPERATURE\0",\
                "TEND\0",\
                "TERM\0",\
                "TERMS\0",\
                "TERRIBLE\0",\
                "TEST\0",\
                "TEXT\0",\
                "THAN\0",\
                "THANK\0",\
                "THANKS\0",\
                "THAT\0",\
                "THE\0",\
                "THEATRE\0",\
                "THEIR\0",\
                "THEM\0",\
                "THEME\0",\
                "THEMSELVES\0",\
                "THEN\0",\
                "THEORY\0",\
                "THERE\0",\
                "THEREFORE\0",\
                "THESE\0",\
                "THEY\0",\
                "THIN\0",\
                "THING\0",\
                "THINK\0",\
                "THIS\0",\
                "THOSE\0",\
                "THOUGH\0",\
                "THOUGHT\0",\
                "THREAT\0",\
                "THREATEN\0",\
                "THROUGH\0",\
                "THROUGHOUT\0",\
                "THROW\0",\
                "THUS\0",\
                "TICKET\0",\
                "TIME\0",\
                "TINY\0",\
                "TITLE\0",\
                "TO\0",\
                "TODAY\0",\
                "TOGETHER\0",\
                "TOMORROW\0",\
                "TONE\0",\
                "TONIGHT\0",\
                "TOO\0",\
                "TOOL\0",\
                "TOOTH\0",\
                "TOP\0",\
                "TOTAL\0",\
                "TOTALLY\0",\
                "TOUCH\0",\
                "TOUR\0",\
                "TOWARDS\0",\
                "TOWN\0",\
                "TRACK\0",\
                "TRADE\0",\
                "TRADITION\0",\
                "TRADITIONAL\0",\
                "TRAFFIC\0",\
                "TRAIN\0",\
                "TRAINING\0",\
                "TRANSFER\0",\
                "TRANSPORT\0",\
                "TRAVEL\0",\
                "TREAT\0",\
                "TREATMENT\0",\
                "TREATY\0",\
                "TREE\0",\
                "TREND\0",\
                "TRIAL\0",\
                "TRIP\0",\
                "TROOP\0",\
                "TROUBLE\0",\
                "TRUE\0",\
                "TRUST\0",\
                "TRUTH\0",\
                "TRY\0",\
                "TURN\0",\
                "TWICE\0",\
                "TYPE\0",\
                "TYPICAL\0",\
                "UNABLE\0",\
                "UNDER\0",\
                "UNDERSTAND\0",\
                "UNDERSTANDING\0",\
                "UNDERTAKE\0",\
                "UNEMPLOYMENT\0",\
                "UNFORTUNATELY\0",\
                "UNION\0",\
                "UNIT\0",\
                "UNITED\0",\
                "UNIVERSITY\0",\
                "UNLESS\0",\
                "UNLIKELY\0",\
                "UNTIL\0",\
                "UP\0",\
                "UPON\0",\
                "UPPER\0",\
                "URBAN\0",\
                "US\0",\
                "USE\0",\
                "USED\0",\
                "USEFUL\0",\
                "USER\0",\
                "USUAL\0",\
                "USUALLY\0",\
                "VALUE\0",\
                "VARIATION\0",\
                "VARIETY\0",\
                "VARIOUS\0",\
                "VARY\0",\
                "VAST\0",\
                "VEHICLE\0",\
                "VERSION\0",\
                "VERY\0",\
                "VIA\0",\
                "VICTIM\0",\
                "VICTORY\0",\
                "VIDEO\0",\
                "VIEW\0",\
                "VILLAGE\0",\
                "VIOLENCE\0",\
                "VISION\0",\
                "VISIT\0",\
                "VISITOR\0",\
                "VITAL\0",\
                "VOICE\0",\
                "VOLUME\0",\
                "VOTE\0",\
                "WAGE\0",\
                "WAIT\0",\
                "WALK\0",\
                "WALL\0",\
                "WANT\0",\
                "WAR\0",\
                "WARM\0",\
                "WARN\0",\
                "WASH\0",\
                "WATCH\0",\
                "WATER\0",\
                "WAVE\0",\
                "WAY\0",\
                "WE\0",\
                "WEAK\0",\
                "WEAPON\0",\
                "WEAR\0",\
                "WEATHER\0",\
                "WEEK\0",\
                "WEEKEND\0",\
                "WEIGHT\0",\
                "WELCOME\0",\
                "WELFARE\0",\
                "WELL\0",\
                "WEST\0",\
                "WESTERN\0",\
                "WHAT\0",\
                "WHATEVER\0",\
                "WHEN\0",\
                "WHERE\0",\
                "WHEREAS\0",\
                "WHETHER\0",\
                "WHICH\0",\
                "WHILE\0",\
                "WHILST\0",\
                "WHITE\0",\
                "WHO\0",\
                "WHOLE\0",\
                "WHOM\0",\
                "WHOSE\0",\
                "WHY\0",\
                "WIDE\0",\
                "WIDELY\0",\
                "WIFE\0",\
                "WILD\0",\
                "WILL\0",\
                "WIN\0",\
                "WIND\0",\
                "WINDOW\0",\
                "WINE\0",\
                "WING\0",\
                "WINNER\0",\
                "WINTER\0",\
                "WISH\0",\
                "WITH\0",\
                "WITHDRAW\0",\
                "WITHIN\0",\
                "WITHOUT\0",\
                "WOMAN\0",\
                "WONDER\0",\
                "WONDERFUL\0",\
                "WOOD\0",\
                "WORD\0",\
                "WORK\0",\
                "WORKER\0",\
                "WORKING\0",\
                "WORKS\0",\
                "WORLD\0",\
                "WORRY\0",\
                "WORTH\0",\
                "WOULD\0",\
                "WRITE\0",\
                "WRITER\0",\
                "WRITING\0",\
                "WRONG\0",\
                "YARD\0",\
                "YEAH\0",\
                "YEAR\0",\
                "YES\0",\
                "YESTERDAY\0",\
                "YET\0",\
                "YOU\0",\
                "YOUNG\0",\
                "YOUR\0",\
                "YOURSELF\0",\
                "YOUTH"};

    euler42(words);

    end = clock();
    double duration = ((double)end - start)/CLOCKS_PER_SEC;
    printf("\nTime taken to execute in seconds : %f\n", duration);
    return EXIT_SUCCESS;
}